//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Магазин2Entities : DbContext
    {
        public Магазин2Entities()
            : base("name=Магазин2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        //public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        //public virtual DbSet<Клиенты> Клиенты { get; set; }
        //public virtual DbSet<Отделы> Отделы { get; set; }
        //public virtual DbSet<Поставщики> Поставщики { get; set; }
        //public virtual DbSet<Поступления> Поступления { get; set; }
        //public virtual DbSet<Продажи> Продажи { get; set; }
        //public virtual DbSet<Самый_дорогой_товар> Самый_дорогой_товар { get; set; }
        //public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        //public virtual DbSet<Товары> Товары { get; set; }
    }
}
