//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставщики
    {
        public int Поставщик_ID { get; set; }
        public string Организация { get; set; }
        public string Телефон { get; set; }
        public string Адрес { get; set; }
    }
}
