//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поступления
    {
        public int Код { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Товар_ID { get; set; }
        public Nullable<int> Кол_во { get; set; }
        public Nullable<decimal> Цена { get; set; }
    }
}
