//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажи
    {
        public int Код { get; set; }
        public Nullable<int> Товар { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> Клиент_ID { get; set; }
        public Nullable<int> Сотрудник_ID { get; set; }
        public Nullable<int> Номер_продажи { get; set; }
        public Nullable<System.DateTime> Дата_продажи { get; set; }
    }
}
