//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public int Сотрудник_ID { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<int> Отдел_ID { get; set; }
        public string Адрес { get; set; }
        public Nullable<System.DateTime> Дата_приема { get; set; }
        public Nullable<int> Пароль { get; set; }
    }
}
