//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        public int Товар_ID { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public int Поставщик_ID { get; set; }
        public Nullable<int> Отдел_ID { get; set; }
    }
}
